-- CREATE TABLE chamados(
--     id SERIAL PRIMARY KEY,
--     equipamento VARCHAR(50) NOT NULL,
--     setor VARCHAR (50) NOT NULL,
--     descricao VARCHAR (150) NOT NULL,
--     prioridade VARCHAR (100) NOT NULL,
--     status VARCHAR (50) NOT NULL
-- );